let x=`       ****************************      `;
let y=`             🆁🅴🅿🅾🆁🆃 🅲🅰🆁🅳             `;
let z=`       ****************************      `;
console.log(x+"\n"+y+"\n"+z);
let name="NAME : 𝘢𝘳𝘵𝘪" ;
let school = "SCHOOL: ⓓⓟⓢ";
let grade="GRADE : A";
let section="SECTION : 2nd";
let roll="ROLL NO : 219";
let sub1="SUB1_MARKS : 89";
let sub2="SUB2_MARKS : 87";
let sub3="SUB3_MARKS : 81";
console.log(name);
console.log(school);
console.log(grade);
console.log(section);
console.log(roll);
console.log(sub1);
console.log(sub2);
console.log(sub3);